# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Docker Build and Push Toolchain'
      inputs:
        containerRegistry: 'Rob Docker Hub'
        repository: catofstealth/kallistios
        Dockerfile: '$(Build.SourcesDirectory)/gcc-toolchain/Dockerfile'
        buildContext: '**'
        tags: |
          toolchain-$(Build.BuildNumber)
          toolchain-latest
